# pod-viewer-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-user-pod-viewer-binding
  namespace: development
subjects:
  - kind: User
    name: dev-user # Name of the user as defined in your authentication system
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-viewer-role # Must match the name of the Role defined above
  apiGroup: rbac.authorization.k8s.io
